"""
Central paths and constants for the artifact pipeline.

All steps import from here so the data layout is defined in ONE place.
The layout is decoupled from the original study's MySQL database: every step
reads and writes CSVs under ``data/``.
"""

import sys as _sys
from pathlib import Path

# Make stdout/stderr UTF-8 so Unicode in prints (arrows, box chars, German
# umlauts in label names) never crashes on a cp1252 Windows console.
for _stream in (_sys.stdout, _sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except Exception:
        pass

# ── Roots ─────────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

# ── Inputs / intermediate products (shipped) ──────────────────────────────────
EXPERIMENTS_DIR = DATA / "experiments"        # raw LLM run CSVs (input to step 5 intra)
INTRA_DIR       = DATA / "intra_LLM"          # per-model aggregated + ICR (step 5 intra output)
INTER_DIR       = DATA / "inter_LLM"          # cross-model final + ICR + human reannotation
REFERENCE_EXCEL = DATA / "reference_paper" / "Evaluationen3.xlsx"
PROMPT_TEMPLATE = DATA / "prompt_templates" / "prompt_template_1.md"

# ── Outputs (regenerated by the pipeline) ─────────────────────────────────────
DESCRIPTIVE_DIR = DATA / "descriptive"        # step 3 figures
SECONDARY_DIR   = DATA / "secondary_analysis" # step 6 outputs

# ── Full texts (NEVER shipped) ────────────────────────────────────────────────
# Step 1 writes the preprocessed paper texts here when a reviewer supplies the
# paper PDF folder. This directory is .gitignore'd and must stay out of the repo.
PREPROCESSED_DIR = DATA / "preprocessed"

# ── Test sandbox (NEVER shipped) ──────────────────────────────────────────────
# --test-configuration writes EVERYTHING (preprocessed texts, annotations, intra
# aggregation) under this temp folder — OUTSIDE data/ — so the published artifact
# dataset is never populated by a test run. .gitignore'd.
TEST_DIR = ROOT / "tmp" / "test_run"

# Number of papers used by --test-configuration.
TEST_N_PAPERS = 5

# ── The key shipped artifact (final aggregated labels) ────────────────────────
FINAL_CSV = INTER_DIR / "df_llm_experiments_final_aggregated_results_prompt_template_1.csv"
HUMAN_REANNOTATION_CSV = INTER_DIR / "df_human_reannotation_results.csv"

# ── Models / template ─────────────────────────────────────────────────────────
PROMPT_TEMPLATE_NAME = "prompt_template_1"

# short name -> full model id (order matters: mistral, llama, gemma).
# These IDs match the SHIPPED experiment files in data/experiments/ and are what
# step 5 uses to read them. Do NOT change them, or the shipped data won't be found.
MODELS = {
    "mistral": "mistral-large-3-675b-instruct-2512",
    "llama":   "llama-3.1-sauerkrautlm-70b-instruct",
    "gemma":   "gemma-3-27b-it",
}

# Current model IDs for NEW annotation runs against the live SAIA API (step 2 /
# --test-configuration). The Llama model was upgraded from
# llama-3.1-sauerkrautlm-70b-instruct to llama-3.3-70b-instruct after the provider
# deprecated the former (see the RIGHT/IEEE companion paper, pub_rse_methodology/ieee.qmd).
# The shipped labels still use the old ID above; live re-runs must use these.
LIVE_MODELS = {
    "mistral": "mistral-large-3-675b-instruct-2512",
    "llama":   "llama-3.3-70b-instruct",
    "gemma":   "gemma-3-27b-it",
}

# Repeated runs per model; majority vote across runs (intra) and across models (inter).
N_RUNS = 3

# ── Label column definitions (shared across steps) ────────────────────────────
BINARY_COLS = [
    "label_forschungssoftware",
    "label_software_evaluation",
    "label_lehr_lern_setting",
]
ORDINAL_COLS = [
    "label_prozess_paradigma",
    "label_lernende_paradigma",
    "label_design_paradigma",
    "label_bildungstechnologie_paradigma",
]
METADATA_COLS = [
    "id", "title", "authors", "year", "start_page", "end_page", "subject",
    "filename", "editors", "doi", "isbn", "issn", "proceeding_title",
    "series_title", "publisher", "publication_place", "conference_date",
    "conference_location", "session_title", "publication_type", "language",
    "peer_review_status",
]

# Columns that hold copyrighted paper FULL TEXT and must never appear in data/.
# (The original experiments.py drops exactly these before saving "for legal reasons".)
FULLTEXT_COLUMNS = {
    "abstract", "text", "references", "main_content",
    "full_text", "fulltext", "content", "body", "raw_text", "paper_text",
}
